input {
  udp {
    port => 5959
    codec => json
  }
}

filter {
  if [logger_name] {
    mutate {
      add_field => { "service" => "turassist" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "turassist-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}